<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<li><img src="<?php echo $this->getBannerSrc() ?>" alt="Payline" /></li>
		<?php $payments = $this->getPaymentMethods();?>
		<?php foreach ($payments as $p): ?>
		<li>
                    <label>
			<input type="radio" value="<?php echo $p['number'] ?>" name="payment[cc_type]" class="radio validate-one-required-by-name"/>
			<img src="<?php echo $this->getLogoUrl($p['type'])?>" alt="<?php echo strtoupper($p['name']) ?>" />
                    </label>
		</li>
		<?php endforeach; ?>
        <li>
            <?php echo $this->getRedirectMessage() ?>
        </li>
    </ul>
</fieldset> 