<?php 
$groups = Mage::getStoreConfig('b2bcheckout/parameters/groups');
$customerGroup = Mage::helper('customer')->getCustomer()->getGroupId();
	
if(((Mage::getStoreConfig('b2bcheckout/parameters/groups_enabled') && in_array($customerGroup,explode(',',$groups))) || !Mage::getSingleton('customer/session')->isLoggedIn() || !Mage::getStoreConfig('b2bcheckout/parameters/groups_enabled')) && Mage::getStoreConfig('b2bcheckout/parameters/enabled') ){
?>
<script type="text/javascript">
//<![CDATA[         
   var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');         
	payment.currentMethod = "checkmo";           
//]]>
</script>
<form action="" id="co-payment-form">
	<input type="hidden" name="payment[method]" value="checkmo" id="p_method_checkmo" >
</form>
<?php 
}
?>
<?php if(Mage::getStoreConfig('b2bcheckout/parameters/enabled') && !Mage::getStoreConfig('b2bcheckout/parameters/skip_shipping') && Mage::getStoreConfig('b2bcheckout/parameters/skip_payment')    ){ ?>
<script type="text/javascript">
//<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
//]]>
</script>
<?php } ?>
