<script type="text/javascript">
//<![CDATA[
    
    function paylineTrySkipPaymentMethod() {
        if (!paylinePaymentSavedTransport) {
            return;
        }
        var paylinePaymentInputNames = [];
        var paylineIsUniquePaymentChoice = true;
        // retrive all radio groups
        $$('#opc-payment input[type=radio]').each(function (radio) {
            if (paylinePaymentInputNames.indexOf(radio.name)==-1)
                paylinePaymentInputNames.push(radio.name);
            else
                paylineIsUniquePaymentChoice = false;
        });
        
        // if only one input by group
        if (paylineIsUniquePaymentChoice) {
            // check all boxes
            paylinePaymentInputNames.each(function (name) {
                $$('#opc-payment input[name="' + name + '"]').first().checked = true;
            });
            // go to review step
            checkout.setStepResponse(paylinePaymentSavedTransport);
        }
    }

    /**
     * This is a bugfix.
     * Instead of doing a double up(), we do a up('li'), which is more precise and to get the good element.
     * After replacing the method, we need to re-bind the click handle with the new method.
     */
    if (Checkout !== undefined) {

        /**
         * Section header click handler
         *
         * @param event
         */
        Checkout.prototype._onSectionClick = function(event) {
            var section = $(Event.element(event).up('li'));
            if (section.hasClassName('allow')) {
                Event.stop(event);
                this.gotoSection(section.readAttribute('id').replace('opc-', ''), false);
                return false;
            }
        };

        // We need to re-bind the click handle on the sections
        Checkout.prototype.rebindSections = function () {
            this.accordion.sections.each(function(section) {
                Event.stopObserving($(section).down('.step-title'), 'click'); // Stop observing
                // Observe again but with the good method ;)
                Event.observe($(section).down('.step-title'), 'click', this._onSectionClick.bindAsEventListener(this));
            }.bind(this));
        };
        if (checkout !== undefined) {
            // Call the rebind method
            checkout.rebindSections();
        }

    }
    
//]]>
</script>
