<div id="back-ajax-add" class="back-ajax-add" style="height: 60px;">
<button class="button left" type="button" href="javascript:void(0);" title="<?php echo $this->__('Continue shopping');?>" onclick="hideMdlOverlay();"><span><span><?php echo $this->__('Continue shopping');?></span></span></buton>
    <a style="color: white;" href="<?php echo $this->getUrl('checkout/cart'); ?>"><button class="button right" type="button" title="<?php echo $this->__('View cart & checkout');?>"><span><span><?php echo $this->__('View cart & checkout');?></span></span></button></a>
<div class="clearfix"></div>
</div>

<div id="cart_content" class="cart_content"><?php
$count = Mage::helper('checkout/cart')->getSummaryCount();

if( $count == 1 ) {
    echo $this->__('My Cart (%s item)', $count);
} elseif( $count > 0 ) {
    echo $this->__('My Cart (%s items)', $count);
} else {
    echo $this->__('My Cart');
}
?></div>
<div class="cart_side_ajax">
    <?php echo $this->getChildHtml('cart_sidebar_ajax') ?>
</div>
<div class="mdl_ajax_message">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="mdl_full_cart_content" id="mdl_full_cart_content">
    <?php echo $this->getChildHtml('cart_content_ajax');?>
</div>