<?php
/**
 * Visualize Your Attributes - Color Swatch
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Icon
 * @version      3.1.15
 * @license:     hlC9gt9cdSBrS26S2Ln1ysO97rKL4VLtOdRx2Aycga
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
$_product = $this->getProduct();
Mage::helper('adjicon')->init(array($_product));
$icons = Mage::helper('adjicon')->display($_product);
?>
<script type="text/javascript">
    var adjIcons = <?php echo Mage::helper('core')->jsonEncode($icons) ?>;
    $$('.product-name').first().insert({after: adjIcons});
</script>