

<section class="" id="owl-categories">

            <div class="owl-item"><div class="carousel__slide">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(10)->getUrl(); ?>" class="carousel__inner" id="bx_3218110189_1746">
                        <div class="carousel__image">
                            <img src="/skin/frontend/simonshop/default/images/marcel/home-carousel-6s.jpg" alt="<?php echo $this->__('Leather cases for iPhone 6/6S'); ?>">
                        </div>
                        <div class="carousel__title"><?php echo $this->__('Leather cases for iPhone 6/6S'); ?></div>
                        <div class="carousel__text"><?php echo $this->__('The thinnest case for the New IPHONE 6S!'); ?></div>
                    </a>
                </div></div>
            <div class="owl-item"><div class="carousel__slide">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(9)->getUrl(); ?>" class="carousel__inner" id="bx_3218110189_1744">
                        <div class="carousel__image">
                            <img src="/skin/frontend/simonshop/default/images/marcel/home-carousel-5s.jpg" alt="<?php echo $this->__('Leather cases for iPhone 5/5S'); ?>">
                        </div>
                        <div class="carousel__title"><?php echo $this->__('Leather cases for iPhone 5/5S'); ?></div>
                        <div class="carousel__text"><?php echo $this->__('The most popular case for IPhone 5'); ?></div>
                    </a>
                </div></div>
            <div class="owl-item"><div class="carousel__slide">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(16)->getUrl(); ?>" class="carousel__inner" id="bx_3218110189_1748">
                        <div class="carousel__image">
                            <img src="/skin/frontend/simonshop/default/images/marcel/home-carousel-watch-42.jpg" alt="<?php echo $this->__('Straps for AppleWatch 42mm'); ?>">
                        </div>
                        <div class="carousel__title"><?php echo $this->__('Straps for AppleWatch 42mm'); ?></div>
                        <div class="carousel__text"></div>
                    </a>
                </div>
            </div>
            <div class="owl-item"><div class="carousel__slide">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(15)->getUrl(); ?>" class="carousel__inner" id="bx_3218110189_1747">
                        <div class="carousel__image">
                            <img src="/skin/frontend/simonshop/default/images/marcel/home-carousel-watch-38.jpg" alt="<?php echo $this->__('Straps for AppleWatch 38mm'); ?>">
                        </div>
                        <div class="carousel__title"><?php echo $this->__('Straps for AppleWatch 38mm'); ?></div>
                        <div class="carousel__text"></div>
                    </a>
                </div>
            </div>
            <div class="owl-item"><div class="carousel__slide">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(11)->getUrl(); ?>" class="carousel__inner" id="bx_3218110189_1745">
                        <div class="carousel__image">
                            <img src="/skin/frontend/simonshop/default/images/marcel/home-carousel-6splus.jpg" alt="<?php echo $this->__('Leather cases for iPhone 6 Plus/ 6S Plus'); ?>">
                        </div>
                        <div class="carousel__title"><?php echo $this->__('Leather cases for iPhone 6 Plus/ 6S Plus'); ?></div>
                        <div class="carousel__text"><?php echo $this->__('Thin, technological and aesthetic covers of high quality leather types and different colors.'); ?></div>
                    </a>
                </div>
            </div>
</section>

