<?php
/**
 * Visualize Your Attributes - Color Swatch
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Icon
 * @version      3.1.15
 * @license:     hlC9gt9cdSBrS26S2Ln1ysO97rKL4VLtOdRx2Aycga
 * @copyright:   Copyright (c) 2015 AITOC, Inc. (http://www.aitoc.com)
 */
$items        = $this->getItems();
$displayStyle = $this->getColumnsNum();
$iconColor    = $this->getIconColor();
$textColor    = $this->getIconTextColor();
$helper       = Mage::helper('adjicon');
?>
<ol>
    <?php if(1 == $displayStyle || AdjustWare_Icon_Helper_Data::VISUALIZATION_TYPE_NONE == $this->getVisualizationType()): // one column ?>
        <?php foreach ($items as $_item): ?>
            <li><?php echo $helper->collectAttributeFilterItems($_item, $this) ?></li>
        <?php endforeach ?>
    <?php elseif(2 == $displayStyle): // only images ?>
        <li>
            <?php foreach($items as $_item) echo $helper->collectAttributeFilterItems($_item, $this) ?>
        </li>
    <?php endif ?>
</ol>