
<?php

$catId = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
// check if the category exists
$categoryExists = Mage::getModel('catalog/category')->load($catId);


    $_productCollection = $this->getLoadedProductCollection();
//    $_productCollection->addAttributeToSelect('color');  
//    $_productCollection->addAttributeToSelect('material'); 
    $columnCount = mdlList('column_count');
    $this->setColumnCount($columnCount);
    $_helper = $this->helper('catalog/output');
    ?>
    <!--code start-->
    <?php
    $customBlock = $this->getLayout()->createBlock('core/template');
    echo $customBlock->setTemplate('marcel/attributes.phtml')->toHtml();

/*
* BIG IF
* if we are on All Products page and no filter is chosen,
* then display the featured products,
* otherwise filter on all products
* */
    $extra_featured_class = '';
if($catId == 2 && (!isset($_GET['color']) && !isset($_GET['material']))) {
    $attribute_code = "mdl_featured";
    $attribute_details = Mage::getSingleton("eav/config")->getAttribute("catalog_product", $attribute_code);
    $options = $attribute_details->getSource()->getAllOptions(false);
    foreach($options as $option){
        if($option["label"]=='Yes')
        {
            $option_value=$option["value"];
        }
    }
    $visibility = array(
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
        Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG

    );
    $_productCollection = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*')->addAttributeToFilter('visibility', $visibility)->addAttributeToFilter('status', 1)->addFieldToFilter('mdl_featured', $option_value);
    $_helper = $this->helper('catalog/output');
    $extra_featured_class = 'featured-all-products';
    $extra_featured_class .= ' featured-count-'.$_productCollection->count();
}
    ?>
    <!--If products are not available-->

    <?php if (!$_productCollection->count()): ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <!--condition end-->
    <?php else: ?>
        <?php $config = Mage::getStoreConfig('mdloption/item_view'); ?>
        <div class="category-products f-block <?php echo $extra_featured_class; ?>">
        <?php if ($config['flip_view'] == 1 && $config['list_flip_view_style'] == 2): ?>
            <?php $flipviewStyleL = 'fadeView'; ?>
        <?php endif; ?>
        <!--Tool bar -->
        <?php echo $this->getToolbarHtml() ?>
        <!--end Tool bar-->
        <!--List View-->
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <?php $imgSize = 192; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?> firstView">
                        <div class="itemInner <?php echo $flipviewStyleL; ?>">
                            <h2 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </h2>
                            <!--Images and price container-->

                            <?php if ($config['flip_view'] == 1): ?>
                                <div class="proImage <?php echo $flipviewStyleL; ?> flipView">
                                    <!--Badge view-->
                                    <div class="badge badge-new-sale">
                                        <?php // if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
                                        <?php if ($_product->getData('new')) {
                                            echo '<span class="new"><img src="' . $this->getSkinUrl('images/marcel/new-en.png') . '" /></span>';
                                        } ?>
                                        <?php //if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
                                        <?php if ($_product->getData('sale')) {
                                            echo '<span class="sale"><img src="' . $this->getSkinUrl('images/marcel/sale-en.png') . '" /></span>';
                                        } ?>
                                    </div>
                                    <!--end badge view-->
                                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                                        <img class="spacer-img"
                                             src="<?php echo $this->getSkinUrl('images/spacer.png'); ?>" title=""
                                             alt=""/>
                                        <span class="face"><img
                                                id="product-collection-image-<?php echo $_product->getId(); ?>"
                                                class="front-img lazy loading"
                                                data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>"
                                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></span>
                            <span class="back-img face back">
                                <img class="hoverImg lazy loading"
                                     data-original="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(300); ?>"
                                     alt="<?php echo $this->htmlEscape($_product['name']); ?>"/>
                            </span>
                                    </a>
                                    <!--Quick view icon-->
                                    <?php if ($config['itemviewbox_quick_view'] == 1): ?>
                                        <a title="<?php echo $this->__('Quick View') ?>"
                                           href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                           class='fancybox qv-btn' id='fancybox<?php echo $_product->getId(); ?>'><i
                                                class="fa fa-search"></i> <?php echo $this->__('Quick View'); ?></a>
                                    <?php endif; ?>
                                    <!--End quick view icon-->
                                </div>
                            <?php else: ?>
                                <div class="proImage">
                                    <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                                        <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                             class="lazy loading"
                                             data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>"
                                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                    </a>
                                    <!--Quick view icon-->
                                    <?php if ($config['itemviewbox_quick_view'] == 1): ?>
                                        <a title="<?php echo $this->__('Quick View') ?>"
                                           href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                           class='fancybox qv-btn' id='fancybox<?php echo $_product->getId(); ?>'><i
                                                class="fa fa-search"></i><?php echo $this->__('Quick View'); ?></a>
                                    <?php endif; ?>
                                    <!--End quick view icon-->
                                </div>
                            <?php endif; ?>

                            <!--End images and price container-->


                            <!--Product detail container-->
                            <div class="bottomProDetail">


                                <!-- Color swatch -->
                                <?php if ($this->getChild('name.after')): ?>
                                    <?php $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren(); ?>
                                    <?php foreach ($_nameAfterChildren as $_nameAfterChildName): ?>
                                        <?php $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName); ?>
                                        <?php $_nameAfterChild->setProduct($_product); ?>
                                        <div class="listColorSwatch">
                                            <?php echo $_nameAfterChild->toHtml(); ?>
                                        </div>
                                    <?php endforeach ?>
                                <?php endif; ?>
                                <!--End Color swatch -->


                                <?php if ($_product->getRatingSummary()): ?>
                                <?php endif; ?>
                                <div class="desc std">
                                    <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped ?>"
                                       class="read-btn"><?php echo $this->__('Read More') ?></a>
                                </div>


                                <!--Price-->
                                <?php echo $this->getPriceHtml($_product, true, '-right') ?>
                                <!--End price-->
                                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <div class="proAction">
                                    <!--Quick view-->
                                    <?php if ($config['itemviewbox_quick_view'] == 1): ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php if (!($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped())): ?>
                                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                        class="add-cart"
                                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                    <span><span><?php echo $this->__('<i class="fa fa-shopping-cart"></i>  Add to cart') ?></span></span>
                                                </button>
                                            <?php else: ?>
                                                <a title="<?php echo $this->__('Add to Cart') ?>"
                                                   href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                                   class='fancybox add-cart'
                                                   id='fancybox<?php echo $_product->getId(); ?>'><span><span><?php echo $this->__('<i class="fa fa-shopping-cart"></i>  Add to cart') ?></span></span></a>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <p class="availability out-of-stock">
                                                <span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                    class="add-cart f-right"
                                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                <span><i
                                                        class="fa fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span>
                                            </button>
                                        <?php else: ?>
                                            <p class="availability out-of-stock">
                                                <span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <!--end quick view-->

                                    <!--Comapare-->
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                        <a title="<?php echo $this->__('Add to Compare') ?>" href="#"
                                           onclick="setLocation('<?php echo $_compareUrl ?>','<?php echo $_product->getId() ?>'); return false;"
                                           class="w-btn"><?php echo $this->__('<i class="fa fa-exchange"></i>') ?></a>
                                    <?php endif; ?>
                                    <!--End comapare-->

                                    <!--wishlist-->
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                           title="<?php echo $this->__('Add to Wishlist') ?>" class="w-btn"><i
                                                class="fa fa-heart"></i></a>
                                    <?php endif; ?>
                                    <!--End wishlist-->

                                </div>
                                <!--End product detail container-->
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
        <?php else: ?>

            <!--end List View-->

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php
            $_columnCount = $this->getColumnCount();
            if ($_columnCount == 4) {
                $listWidth = 'col-xs-6 col-lg-3';
                $imgSize = 155;
            } elseif ($_columnCount == 3) {
                $listWidth = 'col-xs-4 col-sm-4';
                $imgSize = 245;
            }
            ?>

            <!--Grid view-->

            <?php $i = 0; foreach ($_productCollection as $_product): ?>
            <?php if ($i++ % $_columnCount == 0): ?>
            <ul class="products-grid itemPro">
        <?php endif; ?>
            <?php if ($config['itemviewbox'] == 1) {
                $itmeView = 'firstView';
            } elseif ($config['itemviewbox'] == 2) {
                $itmeView = 'secView';
            } else {
                $itmeView = 'thirdView';
            };
            ?>


            <li class="item <?php echo $itmeView; ?> <?php if (($i - 1) % $_columnCount == 0): ?> first <?php elseif ($i % $_columnCount == 0): ?> last <?php endif; ?><?php echo $listWidth ?>">
                <div class="itemInner">
                    <h2 class="product-name">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <?php if ($config['name_character'] != ''): ?>
                                <?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, $config['name_character']) ?>
                            <?php else: ?>
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            <?php endif; ?>
                        </a>
                    </h2>
                    <!--Images and price container-->
                    <div class="proImage <?php echo $flipviewStyleL; ?> flipView">
                        <!--Badge view-->
                        <div class="badge">
                            <?php // if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
                            <?php if ($_product->getData('new')) {
                                echo '<span class="new"><img src="' . $this->getSkinUrl('images/marcel/new-en.png') . '" /></span>';
                            } ?>
                            <?php //if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
                            <?php if ($_product->getData('sale')) {
                                echo '<span class="sale"><img src="' . $this->getSkinUrl('images/marcel/sale-en.png') . '" /></span>';
                            } ?>
                        </div>
                        <!--end badge view-->
                        <?php if ($config['flip_view'] == 1): ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                                <img class="spacer-img" src="<?php echo $this->getSkinUrl('images/spacer.png'); ?>"
                                     title="" alt=""/>
                        <span class="face">
						<img id="product-collection-image-<?php echo $_product->getId(); ?>"
                             class="front-img lazy loading"
                             data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>"
                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
						</span>
                        <span class="back-img back face">
                            <img class="hoverImg lazy loading"
                                 data-original="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(300); ?>"
                                 alt="<?php echo $this->htmlEscape($_product['name']); ?>"/>
                        </span>
                            </a>

                        <?php else: ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     class="lazy loading"
                                     data-original="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250, 300); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            </a>
                        <?php endif; ?>

                        <?php if ($config['itemviewbox'] == 1): ?>
                            <!--Quick view icon-->
                            <?php if ($config['itemviewbox_quick_view'] == 1): ?>
                                <a title="<?php echo $this->__('Quick View') ?>"
                                   href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                   class='fancybox qv-btn' id='itemviewboxfancybox<?php echo $_product->getId(); ?>'><i
                                        class="fa fa-search"></i> <?php echo $this->__('Quick View'); ?></a>
                            <?php endif; ?>
                            <!--End quick view icon-->
                        <?php endif; ?>

                        <!--Quick links-->
                        <?php if ($config['itemviewbox'] == 3): ?>
                            <div class="qlinks">
                                <!--Comapare-->
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <a href="javascript:void(0);" class="w-btn"
                                       onclick="setLocation('<?php echo $_compareUrl ?>','<?php echo $_product->getId() ?>'); return false;">
                                        <i class="fa fa-exchange"></i>
                                    </a>
                                <?php endif; ?>
                                <!--End comapare-->

                                <!--wishlist-->
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                       title="<?php echo $this->__('Add to Wishlist') ?>" class="w-btn">
                                        <i class="fa fa-heart"></i>
                                    </a>
                                <?php endif; ?>
                                <!--End wishlist-->

                                <!--Quick view icon-->
                                <?php if ($config['itemviewbox_quick_view'] == 1): ?>
                                    <a title="<?php echo $this->__('Quick View') ?>"
                                       href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                       class='fancybox w-btn' id='fancybox<?php echo $_product->getId(); ?>'><i
                                            class="fa fa-search"></i></a>
                                <?php endif; ?>
                                <!--End quick view icon-->
                            </div>
                        <?php endif; ?>
                        <!--End Quick links-->

                    </div>
                    <!--End images and price container-->

                    <!--Product detail container-->
                    <div class="bottomProDetail">


                        <!-- Color swatch -->
                        <?php if ($this->getChild('name.after')): ?>
                            <?php $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren(); ?>
                            <?php foreach ($_nameAfterChildren as $_nameAfterChildName): ?>
                                <?php $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName); ?>
                                <?php $_nameAfterChild->setProduct($_product); ?>
                                <div class="listColorSwatch">
                                    <?php echo $_nameAfterChild->toHtml(); ?>
                                </div>
                            <?php endforeach ?>
                        <?php endif; ?>
                        <!--End Color swatch -->

                        <!-- Rating -->
                        <?php echo $this->getReviewsSummaryHtml($_product, "short", true) ?>
                        <!-- End rating -->

                        <!--Price-->
                        <?php echo $this->getPriceHtml($_product, true, '-right') ?>
                        <!--End price-->

                        <div class="proAction">
                            <?php if (($config['itemviewbox'] == 1) || ($config['itemviewbox'] == 3)): ?>

                                <?php if ($config['itemviewbox_quick_view'] == 1): ?>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if (!($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped())): ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                    class="add-cart"
                                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                <span><span><?php echo $this->__('Add to cart') ?></span></span>
                                            </button>
                                        <?php else: ?>
                                            <a title="<?php echo $this->__('Add to Cart') ?>"
                                               href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                               class='fancybox add-cart' id='fancybox<?php echo $_product->getId(); ?>'><span><span><?php echo $this->__('Add to cart') ?></span></span></a>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <p class="availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                class="button"
                                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <?php else: ?>
                                        <p class="availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <!--end quick view-->

                            <?php elseif ($config['itemviewbox'] == 2): ?>
                                <?php if ($config['fp_quick_view'] == 1): ?>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if (!($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped())): ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                    class="w-btn"
                                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                <span><span><i class="fa fa-shopping-cart"></i></span></span></button>
                                        <?php else: ?>
                                            <a title="<?php echo $this->__('Add to Cart') ?>"
                                               href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                               class='fancybox w-btn'
                                               id='fancybox<?php echo $_product->getId(); ?>'><span><span><i
                                                            class="fa fa-shopping-cart"></i></span></span></a>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <p class="availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                <?php else: ?>
                                    <?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                class="w-btn"
                                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                            <span><span><i class="fa fa-shopping-cart"></i></span></span></button>
                                    <?php else: ?>
                                        <p class="availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                <?php endif; ?>

                            <?php endif; ?>



                            <?php if (($config['itemviewbox'] == 1) || ($config['itemviewbox'] == 2)): ?>
                                <!--Comapare-->
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <a href="javascript:void(0);" class="w-btn"
                                       onclick="setLocation('<?php echo $_compareUrl ?>','<?php echo $_product->getId() ?>'); return false;">
                                        <i class="fa fa-signal"></i>
                                    </a>
                                <?php endif; ?>
                                <!--End comapare-->

                                <!--wishlist-->
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                       title="<?php echo $this->__('Add to Wishlist') ?>" class="w-btn">
                                        <i class="fa fa-heart"></i>
                                    </a>
                                <?php endif; ?>
                                <!--End wishlist-->

                                <?php if ($config['itemviewbox'] == 2): ?>
                                    <!--Quick view icon-->
                                    <?php if ($config['itemviewbox_quick_view'] == 1): ?>
                                        <a title="<?php echo $this->__('Quick View') ?>"
                                           href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                           class='fancybox w-btn' id='fancybox<?php echo $_product->getId(); ?>'><i
                                                class="fa fa-search"></i></a>
                                    <?php endif; ?>
                                    <!--End quick view icon-->
                                <?php endif; ?>
                            <?php endif; ?>


                        </div>


                    </div>
                    <!--End product detail container-->
                </div>
            </li>


            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
            </ul>
        <?php endif ?>
        <?php endforeach ?>
            <script
                type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif; ?>
        <div class="toolbar-bottom"> <?php echo $this->getToolbarHtml() ?> </div>
        </div>
    <?php endif; ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
    if ($this->getChild('after')) {
        $_afterChildren = $this->getChild('after')->getSortedChildren();
        foreach ($_afterChildren as $_afterChildName) {
            $_afterChild = $this->getChild('after')->getChild($_afterChildName);
            //set product collection on after blocks
            $_afterChild->setProductCollection($_productCollection);
            echo $_afterChild->toHtml();
        }
    }


?>