<?php $config = Mage::getStoreConfig('mdloption/newpro');?>

<?php if($config['newsettings']):?>
<?php 
  $visibility = array(
	  Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
	  Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
  ); 
  $todayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
  $_productCollection = Mage::getResourceModel('catalog/product_collection')
  ->addAttributeToSelect('*')
  ->addAttributeToFilter('visibility', $visibility)
  ->addAttributeToFilter('status', 1)
  ->addAttributeToFilter('news_from_date', array('date' => true, 'to' => $todayDate))
  ->addAttributeToFilter('news_to_date', array('or'=> array(
  0 => array('date' => true, 'from' => $todayDate),
  1 => array('is' => new Zend_Db_Expr('null')))
  ), 'left');
  $_productCollection->setOrder('entity_id', 'desc');
  $_productCollection->setPageSize($config['newItem']); 
  $_helper = $this->helper('catalog/output');
        //echo 'coun='.count($_productCollection);
 ?>
 
<?php if(count($_productCollection)==0):?>
    <div class="block-title">
     <!-- <h2><span><?php echo $config['newHeadingS']?></span></h2> -->
    </div>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else:?>

<div class="block-title">
<!--  <h2><span><?php echo $config['newHeadingS']?></span></h2> -->
</div>
<div class="jcarousel-wrapper new-products">
  <div class="jcarousel">
    <div class="products-grid latestpro">
      <?php if($config['new_flip_view']==1 && $config['new_flip_view_style']==2):?>
      	<?php $flipviewStylef='fadeView'; ?>
      <?php endif; ?>
      <?php $i=1;foreach($_productCollection as $_productData): ?>
      <?php $_product = Mage::getModel('catalog/product')->load($_productData['entity_id']); ?>
      
       <?php if($config['itemviewbox']==1){
       		$itmeView = 'firstView';
	  	 }elseif($config['itemviewbox']==2){
       		$itmeView = 'secView';
		 }else{
			 $itmeView = 'thirdView';
		 };?>
      
     
      		<div class="item <?php echo $itmeView;?>">
            	<div class="itemInner">
                

                <!--Images and price container-->
               <?php if($config['new_flip_view']==1):?>
               		<div class="proImage <?php echo $flipviewStylef; ?> flipView">
					                <!--Badge view-->
                                    
                	<div class="badge">
						<?php // if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
						<?php  if($_product->getData('new')){echo '<span class="new"><img src="' . $this->getSkinUrl('images/marcel/new-en.png'). '" /></span>';  }?>
                    	<?php //if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
                    	<?php if($_product->getData('sale')){echo '<span class="sale"><img src="' . $this->getSkinUrl('images/marcel/sale-en.png'). '" /></span>';  }?>
	                </div>
                <!--end badge view-->
				
          			<a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
	                    <img class="spacer-img" src="<?php echo $this->getSkinUrl('images/spacer.png');?>" title="" alt="" />
	                    <span class="face">
                        <img id="product-collection-image-<?php echo $_product->getId(); ?>"  class="front-img owl-lazy" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"  /></span>
                        <span class="back-img face back">
                            <img class="hoverImg" src="<?php echo Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(300); ?>" 
                            alt="<?php echo $this->htmlEscape($_product['name']); ?>"  />
                        </span> 
                    </a>
						
                           <?php if($config['itemviewbox']==1):?>
                          <!--Quick view icon-->
							  <?php if($config['new_quick_view']==1):?>
                              <a  title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox qv-btn' id='newfancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i> <?php echo $this->__('Quick View');?></a>
                              <?php endif; ?>
                          <!--End quick view icon-->
                           <?php endif; ?>
                          
                          <!--Quick links-->
                          <?php if($config['itemviewbox']==3):?>
                           <div class="qlinks">
                             <!--Comapare-->
                                 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                      <a href="javascript:void(0);" class="w-btn" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" > 
                                            <i class="fa fa-exchange"></i> 
                                      </a>
                                 <?php endif; ?>
                             <!--End comapare-->
                              
                             <!--wishlist-->
                                  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                  <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="w-btn">
                                     <i class="fa fa-heart"></i>
                                  </a>
                                  <?php endif; ?>
                             <!--End wishlist-->
                             
                             <!--Quick view icon-->
                                  <?php if($config['new_quick_view']==1):?>
                                  <a   title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox w-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
                                  <?php endif; ?>
                             <!--End quick view icon-->
                            </div> 
                          <?php endif; ?> 
                          <!--End Quick links-->
                           

                    </div>
          			<?php else: ?>
                    <div class="proImage">
					                <!--Badge view-->
                	<div class="badge">
						<?php if($_product->getData('new')){echo '<span class="new"><b>'. $_product->getAttributeText('new').'</b><strong>'.$this->__('new').'</strong></span>';  }?>
                    	<?php if($_product->getData('sale')){echo '<span class="sale"><b>'. $_product->getAttributeText('sale').'</b><strong>'.$this->__('sale').'</strong></span>';  }?>
	                </div>
                <!--end badge view-->
					
          				<a href="<?php echo $_product->getProductUrl() ?>" class="product-image"> 
          					<img class="owl-lazy" data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                        </a>
                          <!--Quick view icon-->
							  <?php if($config['new_quick_view']==1):?>
                              <a  title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox qv-btn' id='newfancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i> <?php echo $this->__('Quick View');?></a>
                              <?php endif; ?>
                          <!--End quick view icon--> 
                          
                           <!--Quick links-->
                          <?php if($config['itemviewbox']==3):?>
                           <div class="qlinks">
                             <!--Comapare-->
                                 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                      <a href="javascript:void(0);" class="w-btn" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" > 
                                            <i class="fa fa-exchange"></i> 
                                      </a>
                                 <?php endif; ?>
                             <!--End comapare-->
                              
                             <!--wishlist-->
                                  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                  <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="w-btn">
                                     <i class="fa fa-heart"></i>
                                  </a>
                                  <?php endif; ?>
                             <!--End wishlist-->
                             
                             <!--Quick view icon-->
                                  <?php if($config['new_quick_view']==1):?>
                                  <a   title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox w-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
                                  <?php endif; ?>
                             <!--End quick view icon-->
                            </div> 
                          <?php endif; ?> 
                          <!--End Quick links-->
                          
                </div>
          		<?php endif; ?>

				<!--End images and price container-->  
                <!--Product detail container-->              
                <div class="bottomProDetail">
					
					<h2 class="product-name"> 
                    		<?php if($config['name_character']!=''):?>
                            	<?php echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'),0, $config['name_character'])?>
                            <?php else:?>
                            	<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?> 
                            <?php endif;?> 
                    </h2>
					
					<!-- Color swatch -->
					<?php if ($this->getChild('name.after')):?>
                        <?php $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();?>
                        <?php foreach ($_nameAfterChildren as $_nameAfterChildName):?>
                            <?php $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);?>
                            <?php $_nameAfterChild->setProduct($_product);?>
							<div class="listColorSwatch">
                            <?php echo $_nameAfterChild->toHtml();?>
							</div>
                        <?php endforeach ?>
                    <?php endif;?>
					 <!--End Color swatch -->
                    
					<!-- Rating -->
                        <?php echo $this->getReviewsSummaryHtml($_product, "short", true)?>
                    <!-- End rating -->
					
                    <!--Price-->  
                        <?php echo $this->getPriceHtml($_product, true, '-right') ?>
                    <!--End price--> 
					
                    <div class="proAction">
                    	<?php if(($config['itemviewbox']==1)||($config['itemviewbox']==3)):?>
                        
							  <?php if($config['new_quick_view']==1):?>
								  <?php if($_product->isSaleable()): ?>
									  <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                                      <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="add-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to cart') ?></span></span></button>
                                      <?php else: ?>
                                      <a title="<?php echo $this->__('Add to Cart') ?>"  href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox add-cart' id='fancybox<?php echo $_product->getId();?>'><span><span><?php echo $this->__('Add to cart') ?></span></span></a>
                                      <?php endif; ?>
                                  <?php else: ?>
                                  	   <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                  <?php endif; ?>
                              <?php else: ?>
								  <?php if($_product->isSaleable()): ?>
                                  <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                  <?php else: ?>
                                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                  <?php endif; ?>
                              <?php endif; ?>
                         <!--end quick view-->
                         
                       <?php elseif($config['itemviewbox']==2):?>
                       			<?php if($config['fp_quick_view']==1):?>
                                      <?php if($_product->isSaleable()): ?>
                                          <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
                                          <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="w-btn" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i></span></span></button>
                                          <?php else: ?>
                                          <a title="<?php echo $this->__('Add to Cart') ?>"  href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox w-btn' id='fancybox<?php echo $_product->getId();?>'><span><span><i class="fa fa-shopping-cart"></i></span></span></a>
                                          <?php endif; ?>
                                      <?php else: ?>
                                           <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                      <?php endif; ?>
                                  <?php else: ?>
                                      <?php if($_product->isSaleable()): ?>
                                      <button  type="button" title="<?php echo $this->__('Add to Cart') ?>" class="w-btn" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><i class="fa fa-shopping-cart"></i></span></span></button>
                                      <?php else: ?>
                                      <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                      <?php endif; ?>
                                  <?php endif; ?>
                       
                       <?php endif;?>  
                         
                         
                         
                        <?php if(($config['itemviewbox']==1)||($config['itemviewbox']==2)):?> 
                             <!--Comapare-->
                                 <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                      <a href="javascript:void(0);" class="w-btn" onclick="setLocation('<?php echo $_compareUrl?>','<?php echo $_product->getId()?>'); return false;" > 
                                            <i class="fa fa-signal"></i> 
                                      </a>
                                 <?php endif; ?>
                             <!--End comapare-->
                              
                              <!--wishlist-->
                                  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                  <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>"  class="w-btn">
                                     <i class="fa fa-heart"></i>
                                  </a>
                                  <?php endif; ?>
                              <!--End wishlist-->
                              
                               <?php if($config['itemviewbox']==2):?>
                              <!--Quick view icon-->
                                      <?php if($config['new_quick_view']==1):?>
                                      <a   title="<?php echo $this->__('Quick View')?>" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox w-btn' id='fancybox<?php echo $_product->getId();?>'><i class="fa fa-search"></i></a>
                                      <?php endif; ?>
                              <!--End quick view icon-->
                              <?php endif;?>
                          <?php endif;?> 
                          

                    </div>
                    
                    
                    
                    
                    
                </div>
                <!--End product detail container-->                   
                </div>
            </div>

        
      <?php endforeach ?>
    </div>
  </div>
</div>  
<script type="text/javascript">
(function($){
    $(function() {

		$('.latestpro').owlCarousel({
					loop:true,
					lazyLoad:true,
					smartSpeed: 500,
					dots: false,
					margin:10,
					navText: ["<i class='fa fa-angle-left'></i>", "<i class='fa fa-angle-right'></i>" ],
					responsiveClass:true,
					responsive:{
						0:{
							items:1,
							nav: true
						},
						600:{
							items:3,
							nav: true
						},
						1000:{
							 items:<?php echo $config['newprow'];?>,
							nav: true,
							loop:true
						}
					}
				})
	
	
    });
	
})(jQuery);			
</script>
<?php endif; ?>
<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>

